version: "0.2"
language: en-GB
words:
  - arange
  - argmax
  - astype
  - atran
  - autoupdate
  - azurecr
  - azured
  - bbox
  - bitfields
  - Bitmask
  - blockxsize
  - blockysize
  - Boomitra
  - boto
  - botocore
  - bpglobal
  - bprootca
  - caplog
  - capsys
  - cdist
  - certifi
  - chunksize
  - cleanup
  - cmap
  - cobertura
  - Cobertura
  - colorbar
  - coveragerc
  - cython
  - dask
  - dataframe
  - datetimez
  - Docstyle
  - dotenv
  - Downwelled
  - dropna
  - dtype
  - EDEM
  - edgecolor
  - einops
  - emis
  - emsd
  - epsg
  - EPSG
  - errmsg
  - errorfactory
  - facecolor
  - figsize
  - fillna
  - GDAL
  - geopandas
  - georeferenced
  - geotiff
  - Gerardus
  - getpid
  - getsizeof
  - Hadoop
  - Huadu
  - idxmin
  - iloc
  - imshow
  - inplace
  - ipykernel
  - ipynb
  - ipython
  - isin
  - isna
  - Isort
  - istio
  - junitxml
  - jupyter
  - justfile
  - kubeflow
  - landclass
  - landsat
  - latlon
  - LDCM
  - levelname
  - Liangdu
  - Libertad
  - libexpat
  - lineprecision
  - linewidth
  - lowres
  - lwir
  - Maforki
  - maxx
  - maxy
  - mccabe
  - mininterval
  - miniters
  - miniterval
  - miny
  - mypy
  - nanmax
  - nanmin
  - naturalearth
  - nbstripout
  - ncols
  - ndarray
  - ndvi
  - ntid
  - numpy
  - opencv
  - openssl
  - orthorectified
  - osops
  - Perflint
  - Postgresql
  - postprocess
  - psutil
  - pycache
  - pycodestyle
  - pydantic
  - pydocstyle
  - pyenv
  - pylance
  - Pylint
  - pyproject
  - pystac
  - pytest
  - pythonpath
  - PYTHONPATH
  - pytorch
  - radiometrically
  - rasterio
  - readall
  - readline
  - rechunking
  - reexport
  - referer
  - rioxarray
  - Ruvuma
  - secretkey
  - secretname
  - setuptools
  - shapefile
  - shortwave
  - skipif
  - skipna
  - softmax
  - stac
  - STAC
  - stackstac
  - stddev
  - swarth
  - swir
  - Tambopata
  - teardown
  - toolz
  - torchserve
  - torchvision
  - tqdm
  - tryceratops
  - Upwelled
  - urad
  - urllib
  - USGS
  - venv
  - viridis
  - virtualenv
  - virtualenvs
  - VIRTUALENVS
  - watchexec
  - winge
  - winget
  - xarray
  - xlim
  - ylim
  - zarr
  - ZKSEDEMN
  - zlevel
  - ZSTD
